/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpldesign.com.br.visao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael Paes Leme
 */
public class telaEditarNota extends javax.swing.JFrame {

    /**
     * Creates new form telaEditarNota
     */
    public telaEditarNota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        txtNome = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbxTitulo = new javax.swing.JComboBox<String>();
        jButton3 = new javax.swing.JButton();
        txtID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALTERAR TÍTULO");

        txtTitulo.setBackground(new java.awt.Color(255, 255, 102));
        txtTitulo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        txtTitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EDITAR ANOTAÇÃO");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DESCRIÇÃO DA NOTA");

        txtDescricao.setBackground(new java.awt.Color(255, 255, 102));
        txtDescricao.setColumns(20);
        txtDescricao.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        txtDescricao.setRows(5);
        txtDescricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));
        jScrollPane1.setViewportView(txtDescricao);

        txtNome.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        txtNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNome.setText("Nome e Sobrenome");

        txtData.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        txtData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtData.setText("00-00-0000");

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ALTERAR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("X");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cbxTitulo.setBackground(new java.awt.Color(255, 255, 102));
        cbxTitulo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        cbxTitulo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setBackground(new java.awt.Color(255, 255, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpldesign/com/br/image/icon-buscar.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtID.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTitulo)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(64, 64, 64)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxTitulo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxTitulo)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome)
                    .addComponent(txtData))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
        txtData.setText(formato.format(dataSistema));

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        CarregarCBXNota();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        CarregarUsuario();

        CarregarNota();

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Atualizar();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void Atualizar() {

        try {
            // strings de valores 
            String titulo = txtTitulo.getText();

            // Tratando os valorews inseridos
            if (!titulo.equals("")) {

                // strings de conexão
                //String banco = "jdbc:mysql://localhost/bd_mysql01";
                String banco = "jdbc:mysql://127.0.0.1:3306/agendatecnologica";
                String usuario = "root";
                String senha = "";
                String nomedodriver = "com.mysql.jdbc.Driver";
                Class.forName(nomedodriver).newInstance();
                Connection con = DriverManager.getConnection(banco, usuario, senha);

                // comando sql ATUALIZAÇÃO no banco
                String sql = "UPDATE tb_nota SET "
                        + " titulo=?,"
                        + " descricao=?,"
                        + " nome=?,"
                        + " data=?"
                        + " WHERE "
                        + " id=?";

                //Cria o comando
                PreparedStatement comando = con.prepareStatement(sql);

                //Seta os valores na 
                comando.setString(1, txtTitulo.getText());
                comando.setString(2, txtDescricao.getText());
                comando.setString(3, txtNome.getText());
                String data_registro = txtData.getText();
                DateFormat fmt = new SimpleDateFormat("dd-MM-yyyy");
                java.sql.Date data1 = new java.sql.Date(fmt.parse(data_registro).getTime());
                comando.setDate(4, data1);
                comando.setString(5, txtID.getText());

                //Execulta o comando no banco
                comando.executeUpdate();

                //Fechar as conecções
                comando.close();
                con.close();

                String nome2 = txtNome.getText();
                String titulo2 = txtTitulo.getText();

                //Limpa os campos
                JOptionPane.showMessageDialog(null, "A Nota " + titulo2 + " foi atualizada com Sucesso por " + nome2 + "!");
                LimparCampos();

                CarregarNota();
            } else {
                JOptionPane.showMessageDialog(null, "Informe um nome!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problemas ao tentar conectar com o banco de dados: " + e);
        }

    }

    public void LimparCampos() {

        txtTitulo.setText(null);
        txtDescricao.setText(null);
        txtData.setText(null);
        txtNome.setText(null);
        txtID.setText(null);

    }

    public void CarregarNota() {
        try {
            // strings de valores 
            // strings de conexão
            //String banco = "jdbc:mysql://localhost/bd_mysql01";
            String banco = "jdbc:mysql://127.0.0.1:3306/agendatecnologica";
            String usuario = "root";
            String senha = "";
            String nomedodriver = "com.mysql.jdbc.Driver";
            Class.forName(nomedodriver).newInstance();
            Connection con = DriverManager.getConnection(banco, usuario, senha);

            // comando sql inserção no banco
            String sql = "SELECT * FROM tb_nota";

            //Cria o comando
            PreparedStatement comando = con.prepareStatement(sql);

            ResultSet rs;
            rs = comando.executeQuery();

            cbxTitulo.removeAllItems();

            while (rs.next()) {
                cbxTitulo.addItem(rs.getString("titulo"));

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problemas ao tentar conectar com o banco de dados: " + e);
        }
    }

    public void CarregarCBXNota() {

        String titulo = (String) cbxTitulo.getSelectedItem();

        try {

            if (!titulo.equals("")) {

                String banco = "jdbc:mysql://127.0.0.1:3306/agendatecnologica";
                String usuario = "root";
                String senha = "";
                String nomedodriver = "com.mysql.jdbc.Driver";
                Class.forName(nomedodriver).newInstance();
                Connection con = DriverManager.getConnection(banco, usuario, senha);

                // comando sql inserção no banco
                String sql = "SELECT * FROM tb_nota WHERE titulo = ?";

                //Cria o comando
                PreparedStatement comando = con.prepareStatement(sql);

                comando.setString(1, titulo);

                ResultSet rs;
                rs = comando.executeQuery();

                while (rs.next()) {

                    txtID.setText(rs.getString("id"));
                    txtTitulo.setText(rs.getString("titulo"));
                    txtDescricao.setText(rs.getString("descricao"));

                }

            } else {
                JOptionPane.showMessageDialog(null, "Selecione um Nota!");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public void CarregarUsuario() {
        try {
            // strings de valores 
            // strings de conexão
            //String banco = "jdbc:mysql://localhost/bd_mysql01";
            String banco = "jdbc:mysql://127.0.0.1:3306/agendatecnologica";
            String usuario = "root";
            String senha = "";
            String nomedodriver = "com.mysql.jdbc.Driver";
            Class.forName(nomedodriver).newInstance();
            Connection con = DriverManager.getConnection(banco, usuario, senha);

            // comando sql inserção no banco
            String sql = "SELECT * FROM tb_nomedeacesso";

            //Cria o comando
            PreparedStatement comando = con.prepareStatement(sql);

            ResultSet rs;
            rs = comando.executeQuery();

            txtNome.setText(null);

            while (rs.next()) {
                txtNome.setText(rs.getString("nome"));

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problemas ao tentar conectar com o banco de dados: " + e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaEditarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaEditarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaEditarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaEditarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaEditarNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxTitulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtData;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtNome;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
